#!/bin/bash

# Publish BubbleBox image to a remote registry using Maple
#
# Provide the name of remote registry as an argument
#
maple image build --as-root bubblebox
maple container pour --image=bubblebox
maple container execute "cd cbox/source && make"
maple container execute "python3 setup.py develop && python3 setup.py install && ./setup clean"
maple container commit --image=bubblebox
maple container rinse
maple push bubblebox $1
maple image delete bubblebox
