# Name of the composite action
name: bubblebox

inputs:
  image: 
    description: 'Input image for bubblebox'
    required: true

runs:
  using: "composite"
  steps:
    - run: cd ~/ && git clone https://github.com/akashdhruv/BubbleBox.git
      shell: bash
    - run: cd ~/BubbleBox && maple container pour --image=${{inputs.image}} 
      shell: bash
    - run: cd ~/BubbleBox && maple container execute "./setup develop && ./setup install"
      shell: bash
    - run: cd ~/BubbleBox && maple container commit --image=${{inputs.image}}
      shell: bash
    - run: cd ~/BubbleBox && maple container rinse
      shell: bash
    - run: rm -rf ~/BubbleBox
      shell: bash
