# Name of the composite action
name: bubblebox

inputs:
  image: 
    description: 'Input image for bubblebox'
    required: true

runs:
  using: "composite"
  steps:
    - run: cd ~/work/_actions/akashdhruv/BubbleBox && maple container pour --image=${{inputs.image}} 
      shell: bash
    - run: cd ~/work/_actions/akashdhruv/BubbleBox && maple container execute "./setup develop && ./setup install"
      shell: bash
    - run: cd ~/work/_actions/akashdhruv/BubbleBox && maple container commit --image=${{inputs.image}}
      shell: bash
    - run: cd ~/work/_actions/akashdhruv/BubbleBox && maple container rinse
      shell: bash
