# Name of the composite action
name: install

inputs:
  base-image: 
    description: 'Base image for bubblebox'
    default: 'akashdhruv/bubblebox:latest'

runs:
  using: "composite"
  steps:
    - run: maple image build --base=${{ inputs.base-image }}
      shell: bash
    - run: maple container execute --commit "./setup develop && ./setup install && ./setup clean"
      shell: bash
