name: bubblebox-container

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:
  latest:
    name: "latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Setup BubbleBox env
      run: |
          maple image build
    - name: Run BubbleBox tests
      run: |
          maple container execute "./setup develop && ./setup clean && python3 tests/container"

    - name: Clean BubbleBox env
      run: |
          maple image clean
          maple image remove
