name: bubblebox-container

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:
  latest:
    name: "latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Create local bin
      run: |
          mkdir -p $HOME/.local/bin
          export PATH="PATH:$HOME/.local/bin" 
    - uses: actions/checkout@v2 # checkout root
    - name: Install maple # checkout rest
      run: |
          # If your submodules are configured to use SSH instead of HTTPS
          # please uncomment the following line
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule update --init tools/maple
          cd tools/maple
          ./setup develop
          ./setup clean
    - name: Install dependencies
      run: |
          python3 dependencies.py
    - name: Setup BubbleBox env
      run: |
          cd container
          maple build
    - name: Run BubbleBox tests
      run: |
          cd container
          maple run
    - name: Clean BubbleBox env
      run: |
          cd container
          maple clean
          maple remove
