name: FlashX

on:
  pull_request:
    branches: 
      - main
      - development
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:

  api:
    name: "api"
    runs-on: ubuntu-latest
    steps:
    #- name: Login to Docker Hub
    #  run: |
    #      echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    #- uses: docker/login-action@v1
    #  with:
    #    username: ${{secrets.DOCKER_HUB_USERNAME}}
    #    password: ${{secrets.DOCKER_HUB_PSK}}
    - uses: actions/checkout@v2      
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build flashx --base=${{secrets.DOCKER_HUB_USERNAME}}/boxkit:testing
    - uses: ./.github/actions/install
      with:
        image: flashx
    - name: Run BoxKit tests
      run: |
          maple container pour --image=flashx
          maple container execute "python3 tests/container/heater.py"
          maple container rinse
          maple image delete flashx
