name: Linting

on:
  pull_request:
    branches: 
      - main
      - development
    paths-ignore:
      - '**.rst'
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:

  bin:
    name: "bin"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Install Dependencies
      run: |
          sudo apt-get install -y python3 python3-dev python3-pip
          sudo apt-get install -y python-is-python3
          pip3 install black pylint
          pip3 install -r requirements/core.txt -r requirements/cbox.txt -r requirements/dask.txt -r requirements/pyarrow.txt -r requirements/server.txt -r requirements/analysis.txt -r requirements/zarr.txt
    - name: Run linting 
      run: |
          pylint bin/*.py

  library:
    name: "library"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Install Dependencies
      run: |
          sudo apt-get install -y python3 python3-dev python3-pip
          sudo apt-get install -y python-is-python3
          pip3 install black pylint
          pip3 install -r requirements/core.txt -r requirements/cbox.txt -r requirements/dask.txt -r requirements/pyarrow.txt -r requirements/server.txt -r requirements/analysis.txt -r requirements/zarr.txt
    - name: Run linting 
      run: |
          pylint boxkit/library/*.py

  api:
    name: "api"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Install Dependencies
      run: |
          sudo apt-get install -y python3 python3-dev python3-pip
          sudo apt-get install -y python-is-python3
          pip3 install black pylint
          pip3 install -r requirements/core.txt -r requirements/cbox.txt -r requirements/dask.txt -r requirements/pyarrow.txt -r requirements/server.txt -r requirements/analysis.txt -r requirements/zarr.txt
    - name: Run linting 
      run: |
          pylint boxkit/api/*.py

  resources:
    name: "resources"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Install Dependencies
      run: |
          sudo apt-get install -y python3 python3-dev python3-pip
          sudo apt-get install -y python-is-python3
          pip3 install black pylint
          pip3 install -r requirements/core.txt -r requirements/cbox.txt -r requirements/dask.txt -r requirements/pyarrow.txt -r requirements/server.txt -r requirements/analysis.txt -r requirements/zarr.txt
    - name: Run linting 
      run: |
          pylint boxkit/resources/*.py
          pylint boxkit/resources/*/*.py
