name: Linting

on:
  pull_request:
    branches: 
      - main
      - development
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:

  Linting:
    name: "Check Formatting" 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build boxkit
    - uses: ./.github/actions/install
      with:
        image: boxkit
    - name: Run Linting Tests
      run: |
          maple container pour --image=boxkit
          maple container execute "pip3 install black pylint"
          maple container execute "pylint bin/*.py boxkit/api/*.py boxkit/library/*.py boxkit/resources/read/*.py"
          maple container rinse
          maple image delete boxkit 
