name: Linting

on:
  pull_request:
    branches: 
      - main
      - development
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:

  Linting:
    name: "Check Formatting" 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Install Dependencies
      run: |
          sudo apt-get install -y python3 python3-dev python3-pip
          sudo apt-get install -y python-is-python3
          pip3 install black pylint
    - name: Run linting 
      run: |
          pylint bin/*.py boxkit/api/*.py boxkit/library/*.py boxkit/resources/read/*.py
