name: Minimal

on:
  push:
     - development
  pull_request:
    branches: 
      - main
      - development
    paths-ignore:
      - '**.rst'
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:

  windows:
    name: "windows"
    runs-on: windows-latest
    - uses: actions/checkout@v2      
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build boxkit
    - uses: ./.github/actions/install
      with:
        image: boxkit
    - name: Run BoxKit tests
      run: |
          maple container pour --image=boxkit
          maple container execute "python3 tests/container/create.py"
          maple container rinse
          maple image delete boxkit

  ubuntu: 
    name: "ubuntu" 
    runs-on: ubuntu-latest
    steps:
    #- name: Login to Docker Hub
    #  run: |
    #      echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    #- uses: docker/login-action@v1
    #  with:
    #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #    password: ${{ secrets.DOCKER_HUB_PSK }}
    - uses: actions/checkout@v2      
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build boxkit
    - uses: ./.github/actions/install
      with:
        image: boxkit
    - name: Run BoxKit tests
      run: |
          maple container pour --image=boxkit
          maple container execute "python3 tests/container/create.py"
          maple container rinse
          maple image delete boxkit 
