name: Publish

on:
  workflow_dispatch:

  #push:
  #  branches: 
  #    - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:

  Publish:
    name: "Publish" 
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: |
          echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    - uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PSK}}
    - uses: actions/checkout@v2      
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Publish BoxKit Image
      run: |
          maple image build boxkit --as-root
          maple container publish --image=boxkit 
          maple push boxkit ${{secrets.DOCKER_HUB_USERNAME}}/boxkit:latest
