name: ubuntu-container

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

  #push:
  #  branches: 
  #    - development
  #  paths-ignore:
  #    - '**.md'
  #    - 'LICENSE'
  #    - 'CITATION'

jobs:
  #
  #Job 1
  #
  latest:
    name: "latest" 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: Dependencies1
      run: |
          mkdir -p $HOME/.local/bin
          export PATH="PATH:$HOME/.local/bin"
    - uses: actions/checkout@v2 # checkout root
    - name: Checkout submodules # checkout rest
      run: |
          # If your submodules are configured to use SSH instead of HTTPS 
          # please uncomment the following line
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule update --init tools/maple
          git submodule update --init tools/indicators
          cd tools/maple
          ./setup develop
          ./setup clean
    - name: Setup BubbleBox env
      run: |
          cd container
          maple build --image akashdhruv/ubuntu:latest
    - name: Run BubbleBox tests
      run: |
          cd container
          maple run
    - name: Clean BubbleBox env
      run: |
          cd container
          maple clean
          maple remove --image akashdhruv/ubuntu:latest
